# Form implementation generated from reading ui file 'ui_files/color_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AggregationColorWindow(object):
    def setupUi(self, AggregationColorWindow):
        AggregationColorWindow.setObjectName("AggregationColorWindow")
        AggregationColorWindow.resize(296, 141)
        AggregationColorWindow.setMinimumSize(QtCore.QSize(263, 141))
        AggregationColorWindow.setMaximumSize(QtCore.QSize(16777215, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        AggregationColorWindow.setFont(font)
        AggregationColorWindow.setStyleSheet("QLineEdit, #color_view {\n"
"    min-height: 20px;\n"
"    min-width: 30px;\n"
"    padding: 4px; \n"
"}\n"
"\n"
"#hexcode {\n"
"    font-family: \"Consolas\", \"Monospace\";\n"
"}\n"
"\n"
"#color_view {\n"
"    border: 1px solid rgb(31, 31, 36);\n"
"    border-radius: 4px;\n"
"    background: #282B2B; \n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(AggregationColorWindow)
        self.gridLayout_2.setVerticalSpacing(16)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=AggregationColorWindow)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=AggregationColorWindow)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.hexcode = QtWidgets.QLineEdit(parent=AggregationColorWindow)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.hexcode.setFont(font)
        self.hexcode.setInputMask("")
        self.hexcode.setMaxLength(9)
        self.hexcode.setObjectName("hexcode")
        self.gridLayout.addWidget(self.hexcode, 0, 1, 1, 1)
        self.color_view = QtWidgets.QLabel(parent=AggregationColorWindow)
        self.color_view.setStyleSheet("")
        self.color_view.setText("")
        self.color_view.setObjectName("color_view")
        self.gridLayout.addWidget(self.color_view, 0, 2, 1, 1)
        self.image_url = QtWidgets.QLineEdit(parent=AggregationColorWindow)
        self.image_url.setInputMask("")
        self.image_url.setObjectName("image_url")
        self.gridLayout.addWidget(self.image_url, 1, 1, 1, 3)
        self.color_picker = QtWidgets.QToolButton(parent=AggregationColorWindow)
        self.color_picker.setStyleSheet("")
        self.color_picker.setObjectName("color_picker")
        self.gridLayout.addWidget(self.color_picker, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.add_btn = QtWidgets.QPushButton(parent=AggregationColorWindow)
        self.add_btn.setMinimumSize(QtCore.QSize(100, 32))
        self.add_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.add_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout_2.addWidget(self.add_btn, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)

        self.retranslateUi(AggregationColorWindow)
        QtCore.QMetaObject.connectSlotsByName(AggregationColorWindow)

    def retranslateUi(self, AggregationColorWindow):
        _translate = QtCore.QCoreApplication.translate
        AggregationColorWindow.setWindowTitle(_translate("AggregationColorWindow", "Garment Color"))
        self.label.setText(_translate("AggregationColorWindow", "Código HEX"))
        self.label_2.setText(_translate("AggregationColorWindow", "URL de imagen"))
        self.color_picker.setToolTip(_translate("AggregationColorWindow", "Selector de color"))
        self.color_picker.setText(_translate("AggregationColorWindow", "..."))
        self.add_btn.setText(_translate("AggregationColorWindow", "Agregar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AggregationColorWindow = QtWidgets.QDialog()
    ui = Ui_AggregationColorWindow()
    ui.setupUi(AggregationColorWindow)
    AggregationColorWindow.show()
    sys.exit(app.exec())
